name: Market

version: 0.1

Author: Wooskie

main: me.wooskie.market.Market

commands:

   market:

      description: unfinished market command.

      usage: market usage.

   buy:

      description: This is the unfinished buy command.

      usage: testy testy testy market!

   price:

      description: unfinished price command.

      usage: price usage.
   chest:
      description: unfinished chest command.
      usage: chest usage.